// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package db

import (
	"context"
)

const hasLike = `-- name: HasLike :one
SELECT EXISTS (
    SELECT 1
    FROM likes
    WHERE sender_id = $1
      AND receiver_id = $2
)
`

type HasLikeParams struct {
	SenderID   string
	ReceiverID string
}

// EXISTSは対象が0件ならfalse、1件以上ならtrueというboolean 1行を必ず返す。
func (q *Queries) HasLike(ctx context.Context, arg HasLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLike, arg.SenderID, arg.ReceiverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMatches = `-- name: ListMatches :many
SELECT
  user_low_id,
  user_high_id
FROM matches
WHERE user_low_id = $1
  OR user_high_id = $1
ORDER BY
  user_low_id,
  user_high_id
`

type ListMatchesRow struct {
	UserLowID  string
	UserHighID string
}

func (q *Queries) ListMatches(ctx context.Context, userID string) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesRow
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(&i.UserLowID, &i.UserHighID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatchingPair = `-- name: LockMatchingPair :exec
SELECT pg_advisory_xact_lock(
    hashtext(
        LEAST(
            $1::text,
            $2::text
        )
    ),
    hashtext(
        GREATEST(
            $1::text,
            $2::text
        )
    )
)
`

type LockMatchingPairParams struct {
	FirstUserID  string
	SecondUserID string
}

func (q *Queries) LockMatchingPair(ctx context.Context, arg LockMatchingPairParams) error {
	_, err := q.db.Exec(ctx, lockMatchingPair, arg.FirstUserID, arg.SecondUserID)
	return err
}

const saveLike = `-- name: SaveLike :execrows
INSERT INTO likes (
    sender_id,
    receiver_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (sender_id, receiver_id) DO NOTHING
`

type SaveLikeParams struct {
	SenderID   string
	ReceiverID string
}

func (q *Queries) SaveLike(ctx context.Context, arg SaveLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveLike, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveMatch = `-- name: SaveMatch :execrows
INSERT INTO matches (
    user_low_id,
    user_high_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (user_low_id, user_high_id) DO NOTHING
`

type SaveMatchParams struct {
	UserLowID  string
	UserHighID string
}

func (q *Queries) SaveMatch(ctx context.Context, arg SaveMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveMatch, arg.UserLowID, arg.UserHighID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
