// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Like struct {
	SenderID   string
	ReceiverID string
	CreatedAt  pgtype.Timestamptz
}

type Match struct {
	UserLowID  string
	UserHighID string
	CreatedAt  pgtype.Timestamptz
}

type OutboxEvent struct {
	ID          string
	EventType   string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type User struct {
	ID        string
	CreatedAt pgtype.Timestamptz
}
