// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
)

const saveOutboxEvent = `-- name: SaveOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    event_type,
    payload
) VALUES (
    $1,
    $2,
    $3::jsonb
)
`

type SaveOutboxEventParams struct {
	ID        string
	EventType string
	Payload   []byte
}

func (q *Queries) SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) error {
	_, err := q.db.Exec(ctx, saveOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	return err
}
