// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// EXISTSは対象が0件ならfalse、1件以上ならtrueというboolean 1行を必ず返す。
	HasLike(ctx context.Context, arg HasLikeParams) (bool, error)
	ListMatches(ctx context.Context, userID string) ([]ListMatchesRow, error)
	LockMatchingPair(ctx context.Context, arg LockMatchingPairParams) error
	SaveLike(ctx context.Context, arg SaveLikeParams) (int64, error)
	SaveMatch(ctx context.Context, arg SaveMatchParams) (int64, error)
	SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
